# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDRmMTA3MWUzNmFiMDhmNzNmN2M2YWYxZjUyZmFiMzc5YjkwZmE0NTRjNDkxMjE1YmNmYjg5MjUyNDNhMGY1YWUxMGFmZTY5ZTVlOTNhMTg0NTdhN2EwNjllOWI2NGU1OWJmNjhkMmNmYWQyMzI5YjAzOWM0YTUwYmE2ODdiY2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
